### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by vkrasovskiy-playq** [ahockersten/liero#11]
@ahockersten could you explain what exactly this code in worm.cpp doing?

```
if(reacts[RFDown] < 2)
				{
					if(reacts[RFUp] > 0)
					{
						if(reacts[RFLeft] > 0 || reacts[RFRight] > 0)
						{
							//Low or none push down,
							//Push up and
							//Push left or right

							pos.y -= itof(1);
							next.y = pos.y + vel.y;
							iNext.y = ftoi(next.y);

							calculateReactionForce(game, iNext.x, iNext.y, RFLeft);
							calculateReactionForce(game, iNext.x, iNext.y, RFRight);
						}
					}
				}

				if(reacts[RFUp] < 2)
				{
					if(reacts[RFDown] > 0)
					{
						if(reacts[RFLeft] > 0 || reacts[RFRight] > 0)
						{
							//Low or none push up,
							//Push down and
							//Push left or right

							pos.y += itof(1);
							next.y = pos.y + vel.y;
							iNext.y = ftoi(next.y);

							calculateReactionForce(game, iNext.x, iNext.y, RFLeft);
							calculateReactionForce(game, iNext.x, iNext.y, RFRight);
						}
					}
				}
			}
```

Is it special code for climbing? If not, do you know part of code, which handle moving by ascending surface?
Very appreciate any information. Thanks for great port of awesome game!

**Comment by ahockersten** [comment]
Hello Viktor,
Unfortunately I have only ported the graphical parts of the code, I have never looked into the actual logic, so I can't help you with your question.

**Comment by ahockersten** [comment]
Actually, yes, this code is at least related to what happens when you ascend a surface. One way to see this is to change this line:
`pos.y += itof(1);`

Replace 1 by 10, and you will notice that how ascending works is changed.

**Comment by vkrasovskiy-playq** [comment]
@ahockersten thanks! Sorry for dumb question, but I can't compile your vs project. In file "video_recorder.h" I see unexisted libs...
![image](https://user-images.githubusercontent.com/29615434/39269597-038ab166-48dc-11e8-9f8d-098a4e7b75cf.png)

Error	C1083	Cannot open include file: 'libavformat/avformat.h': No such file or directory	liero_tools	c:\data\unityprojects\liero\src\video_tool\video_recorder.h	6	

So, it is fixable? 😄

**Comment by ahockersten** [comment]
You don't those files unless you want to build the video creation tool. The game itself will build fine without it. If you do want to build the video tool, check out the instructions in the README file, here: https://github.com/ahockersten/liero#optional-dependencies-for-building-the-video-tool

**Comment by vkrasovskiy-playq** [comment]
@ahockersten thanks!

But suddenly I hit another strange error...
![image](https://user-images.githubusercontent.com/29615434/39270472-e07f91de-48de-11e8-8b20-6e210f3c1dff.png)

Can I deal with it? 🤠 
I use vs 2017 and "Visual Studio 2017 - Windows XP (v141_xp)" toolset

**Comment by vkrasovskiy-playq** [comment]
@ahockersten finally I get it. I was set incorrect startup project. My mistake. Thank you very much!
