### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by ahockersten** [ahockersten/liero#6]
We need an icon that should be used both as an icon for the binary and as the icon for the window when running Liero. See discussion in #2 for suggestions on icon to use and requirements on it.

**Comment by emillaine** [comment]
For reference, here's the icon by @TimmermanV:

<img width="152" alt="liero-1 dragged" src="https://cloud.githubusercontent.com/assets/7543552/16743613/e4d35ad0-47b5-11e6-8ed9-8ca629ec5c48.png">

And here's lierolibre's icon:

![lierolibre-icon](https://cloud.githubusercontent.com/assets/7543552/16743941/5ad7c634-47b7-11e6-9612-41cd976e552a.png)

And here are two alternatives I made:

![liero2](https://cloud.githubusercontent.com/assets/7543552/16743760/8f17dd9a-47b6-11e6-8b9c-189fd32b07d9.png)

![liero3](https://cloud.githubusercontent.com/assets/7543552/16743865/06615dc2-47b7-11e6-9912-c14e75ca7a31.png)
